// admin/component/article/ArticleListPage/Dashboard/ArticleList/index.tsx
import React from 'react'

import ArticleCard from '../ArticleCard'
import Slider from '@component/common/Slider'

import { IArticleListProps } from './ArticleList.type'

import variable from '@style/variable'
import { StyledLabel } from './ArticleList.style'

const ArticleList = ({ label, articleList }: IArticleListProps): JSX.Element => {
  const renderContent = (): JSX.Element[] =>
    React.Children.toArray(
      articleList.map(element =>
        <ArticleCard article={element} />
      )
    )

  return (
    <>
      <StyledLabel>{label}</StyledLabel>
      <Slider
        speed={500}
        slidesToShow={3}
        centerMode={true}
        slidesToScroll={3}
        className="center"
        swipeToSlide={true}
        lazyLoad="progressive"
        centerPadding={`${variable.paddingBig}px`}
        responsive={[
          {
            breakpoint: variable.mediumScreen,
            settings: {
              slidesToShow: 2,
              slidesToScroll: 2
            }
          },
          {
            breakpoint: variable.smallScreen,
            settings: {
              slidesToShow: 1,
              slidesToScroll: 1
            }
          }
        ]}
      >
        {renderContent()}
      </Slider>
    </>
  )
}

export default ArticleList

// component/Home/ArticleList.vue
<template>
  <div class="home__article-list">
    <h2 class="article-list__label">
      {{ label }}
    </h2>
    <Slider
      :slidesToShow="6"
      :slidesToScroll="6"
      :responsive="responsive"
    >
      <div v-for="article in articles" :key="article.articleId">
        <ArticleCard :article="article" />
      </div>
      <div v-for="article in articles" :key="article.articleId">
        <ArticleCard :article="article" />
      </div>
    </Slider>
  </div>
</template>

<script>
import Slider from '../common/Slider'
import ArticleCard from '../common/ArticleCard'

import getSliderElements from '@utility/getSliderElements'

export default {
  name: 'ArticleList',
  components: {
    Slider,
    ArticleCard
  },
  data () {
    const smallScreenSliderElements = getSliderElements(this.articles, 2)
    const mediumScreenSliderElements = getSliderElements(this.articles, 3)

    return {
      responsive: [
        {
          breakpoint: 1919,
          settings: {
            slidesToShow: mediumScreenSliderElements,
            slidesToScroll: mediumScreenSliderElements
          }
        },
        {
          breakpoint: 1367,
          settings: {
            centerPadding: '40px',
            slidesToShow: mediumScreenSliderElements,
            slidesToScroll: mediumScreenSliderElements
          }
        },
        {
          breakpoint: 1023,
          settings: {
            centerPadding: '20px',
            slidesToShow: smallScreenSliderElements,
            slidesToScroll: smallScreenSliderElements
          }
        },
        {
          breakpoint: 750,
          settings: {
            slidesToShow: 1,
            slidesToScroll: 1,
            centerMode: false,
            centerPadding: '0px'
          }
        }
      ]
    }
  },
  props: {
    label: { type: String, required: true },
    articles: { type: Array, required: true }
  }
}
</script>
