// admin/page/Error/index.tsx
import React from 'react'
import { useParams, useHistory } from 'react-router-dom'

import Button from '@component/generic/Button'
import Container from '@component/common/Container'

import getErrorMessage from './getErrorMessage'

import routeList from '@config/routeList'

import { StyledCode, StyledWrapper, StyledDescription } from './Error.style'

const Error = (): JSX.Element => {
  const history = useHistory()
  const { code } = useParams<{ code: string }>()

  const handleRefreshClick = (): void => history.push(routeList.base)

  return (
    <Container>
      <StyledWrapper>
        <svg>
          <use xlinkHref="#robot" />
        </svg>
        <StyledCode>{code}</StyledCode>
        <StyledDescription>{getErrorMessage(code)}</StyledDescription>
        <Button onClick={handleRefreshClick}>
          Refresh
        </Button>
      </StyledWrapper>
    </Container>
  )
}

export default Error

// client/page/Error.vue
<template>
  <Container>
    <div class="error-page">
      <RobotSVG class="error-page__icon" />
      <h1 class="error-page__code">{{ code }}</h1>
      <label class="error-page__description">{{ errorMessage }}</label>
      <Button :onClick="handleRefreshClick">Refresh</Button>
    </div>
  </Container>
</template>

<script>
import Button from '@component/generic/Button'
import Container from '@component/common/Container'

import routeList from '@config/routeList'

import RobotSVG from '@asset/svg/robot.svg'

export default {
  name: 'page-error',
  data() {
    return {
      code: Number(this.$route.params.code)
    }
  },
  components: {
    Button,
    RobotSVG,
    Container
  },
  computed: {
    errorMessage() {
      const errorMessages = {
        404: 'Not found.',
        500: 'Internal Server Error.'
      }

      return errorMessages[this.code] || 'An error occured.'
    }
  },
  methods: {
    handleRefreshClick() {
      this.$router.push(routeList.base)
    }
  }
}
</script>
